model:
  seed: 43
  in_channels: 3
  latent_dim: 2
  hidden_dims: [8, 16, 32, 64]
  learning_rate: 0.0005
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  n_samples_to_log_in_val: 5

data:
  generate_data_on_the_fly: True
  existing_data_path:
    shapes: "data/shapes_32x32_60000.npy"
    sources: "data/sources_60000_d=2.npy"
  data_generation_params:
    n_samples: 60000
    render_config:
      canvas_size: 32
      anti_alias: 1
      background_color: "black"
      sample_color: "blue"
    sampler_config:
      type: "uniform"
      params: [0, 1]
  general_data_params:
    train_batch_size: 64
    num_workers: 2
    train_ratio: 0.8
    val_ratio: 0.2
    train_batch_shuffle: True

trainer:
  devices: "auto"
  accelerator: "gpu"
  max_epochs: 100
  strategy: "ddp"
  num_sanity_val_steps: -1
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      log_model: all
      project: "lab_vae"

# early_stopping:
#   monitor: "Validation/ELBO_Loss"
#   mode: "min"
#   patience: 5
#   verbose: True
  
  