manual_seed: 1265

architecture_params:
  in_channels: 3
  latent_dim: 2
  hidden_dims: [8, 16, 32, 64]

opt_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025

data_params:
  shapes_path: "data/shapes_32x32_10000.npy"
  sources_path: "data/sources_10000_d=2.npy"
  train_batch_size: 64
  n_samples: 10000
  num_workers: 1

trainer_params:
  devices: 1
  accelerator: "cpu"
  max_epochs: 100

logging_params:
  name:
  project: "lab_project"
  log_model: "all"
  
  