model:
  seed: 8952
  vae:
    # class_path: models.vanilla_vae.VanillaVAE
    class_path: models.ima_vae.IMA_Vae
    init_args:
      hidden_dims: [8, 16, 32, 64]
      in_channels: 3
      latent_dim: null # Computed according to len(data.data_generation_params.factors)
      decoder_var: 1.0
  learning_rate: 0.0005
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  n_samples_to_log_in_val: 5

data:
  generate_data_on_the_fly: True
  existing_data_path:
    shapes: "/cs/labs/yweiss/adirt/lab_project/vae-lab-project/data/shapes.npy"
    sources: "/cs/labs/yweiss/adirt/lab_project/vae-lab-project/data/sources.npy"
  data_generation_params:
    n_samples: 60000
    factors: ['x', 'y', 'size']
    render_config:
      canvas_size: 64
      anti_alias: 1
      background_color: "black"
      sample_color: "blue"
      sample_color_2: "orange"
    sampler_config:
      type: "uniform"
      params: [0, 1]
  general_data_params:
    train_batch_size: 64
    num_workers: 1
    train_ratio: 0.8
    val_ratio: 0.2
    train_batch_shuffle: True
    save_data: False

trainer:
  devices: auto
  accelerator: gpu
  max_epochs: 200
  strategy: auto
  num_sanity_val_steps: 2
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      log_model: all
      project: "lab_vae_step2"
      tags: ["find_best_seed","3_factors", "size"]

model_checkpoint:
  monitor: "Validation/Mean_Correlation_Coefficient"
  mode: "max"
  verbose: True
  
  